api:
  host: http://trimet.dev.conveyal.com
  path: /otp/routers/default
  port: 8001

map:
  initLat: 45.52
  initLon: -122.682
  initZoom: 12
  #layerCtlPos: 'bottomright'
  zoomCtlPos: null
  baseLayers:
    - name: Streets
      url: //tiled.trimet.org/tilecache/tilecache.py/1.0.0/currentOSM/{z}/{x}/{y}
      attribution: 'Map tiles: <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
      maxZoom: 20
    - name: Aerials
      url: //tiled.trimet.org/tilecache/tilecache.py/1.0.0/hybridOSM/{z}/{x}/{y}
      attribution: 'Map tiles: <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
      maxZoom: 20
    - name: Stamen Streets
      url: //tile.stamen.com/terrain/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
      maxZoom: 17
    - name: Stamen Toner Lite
      url: //tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
      maxZoom: 18


geocoder:
  url: //ws-st.trimet.org/pelias/v1
  attribution: 'Geocoding via Pelias'
  boundary:
    rect:
      minLon: -123.2034
      maxLon: -122.135
      minLat: 45.273
      maxLat: 45.7445
  MAPZEN_KEY: MAPZEN_KEY
  focusPoint:
    lat: 45.5223452
    lon: -122.6821804
  # Optional custom Pelias instance (defaults to Mapzen Search)
  # baseUrl: https://geocoder.example.com/pelias/v1

modeGroups:
  - name: Transit
    modes:
      - TRAM
      - BUS
  - name: Walk/Bike
    modes:
      - WALK
      - BICYCLE
